# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 235)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 151))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(2, 13, 251, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.line1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb1.setObjectName("rb1")
        self.horizontalLayout.addWidget(self.rb1)
        self.rb2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb2.setObjectName("rb2")
        self.horizontalLayout.addWidget(self.rb2)
        self.rb3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb3.setObjectName("rb3")
        self.horizontalLayout.addWidget(self.rb3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 2, 1, 1)
        self.label3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.combobox1 = QtWidgets.QComboBox(self.layoutWidget)
        self.combobox1.setObjectName("combobox1")
        self.combobox1.addItem("")
        self.combobox1.addItem("")
        self.combobox1.addItem("")
        self.gridLayout.addWidget(self.combobox1, 2, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 2, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 202, 261, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button1 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.horizontalLayout_2.addWidget(self.button1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.button2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.horizontalLayout_2.addWidget(self.button2)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 164, 261, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label1_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.horizontalLayout_3.addWidget(self.label1_2)
        self.line2 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.line2.setFont(font)
        self.line2.setObjectName("line2")
        self.horizontalLayout_3.addWidget(self.line2)
        self.label1_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label1_3.setFont(font)
        self.label1_3.setObjectName("label1_3")
        self.horizontalLayout_3.addWidget(self.label1_3)
        self.line3 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.line3.setFont(font)
        self.line3.setObjectName("line3")
        self.horizontalLayout_3.addWidget(self.line3)
        self.label20 = QtWidgets.QLabel(Form)
        self.label20.setGeometry(QtCore.QRect(120, 0, 54, 12))
        self.label20.setText("")
        self.label20.setObjectName("label20")
        self.label21 = QtWidgets.QLabel(Form)
        self.label21.setGeometry(QtCore.QRect(80, 190, 54, 12))
        self.label21.setText("")
        self.label21.setObjectName("label21")

        self.retranslateUi(Form)
        self.button1.clicked.connect(Form.progress1)
        self.button2.clicked.connect(Form.progress2)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.line1, self.rb1)
        Form.setTabOrder(self.rb1, self.rb2)
        Form.setTabOrder(self.rb2, self.rb3)
        Form.setTabOrder(self.rb3, self.combobox1)
        Form.setTabOrder(self.combobox1, self.line2)
        Form.setTabOrder(self.line2, self.line3)
        Form.setTabOrder(self.line3, self.button1)
        Form.setTabOrder(self.button1, self.button2)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "保存"))
        self.groupBox.setTitle(_translate("Form", "保存选项"))
        self.label1.setText(_translate("Form", "隔离开关编号："))
        self.label_2.setText(_translate("Form", "号"))
        self.label.setText(_translate("Form", "            第"))
        self.rb1.setText(_translate("Form", "A"))
        self.rb2.setText(_translate("Form", "B"))
        self.rb3.setText(_translate("Form", "C"))
        self.label2.setText(_translate("Form", "相"))
        self.label3.setText(_translate("Form", "            第"))
        self.combobox1.setItemText(0, _translate("Form", "1"))
        self.combobox1.setItemText(1, _translate("Form", "2"))
        self.combobox1.setItemText(2, _translate("Form", "3"))
        self.label4.setText(_translate("Form", "支"))
        self.button1.setText(_translate("Form", "保存"))
        self.button2.setText(_translate("Form", "取消"))
        self.label1_2.setText(_translate("Form", "备注1："))
        self.label1_3.setText(_translate("Form", "备注2："))

