# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test93.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1598, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("xy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(210, 236, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(344, -4, 1141, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button2 = QtWidgets.QPushButton(self.layoutWidget)
        self.button2.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.button2.setObjectName("button2")
        self.horizontalLayout.addWidget(self.button2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.button3 = QtWidgets.QPushButton(self.layoutWidget)
        self.button3.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.button3.setObjectName("button3")
        self.horizontalLayout.addWidget(self.button3)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.button4 = QtWidgets.QPushButton(self.layoutWidget)
        self.button4.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.button4.setObjectName("button4")
        self.horizontalLayout.addWidget(self.button4)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.button5 = QtWidgets.QPushButton(self.layoutWidget)
        self.button5.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.button5.setObjectName("button5")
        self.horizontalLayout.addWidget(self.button5)
        self.pyqtgraph1 = GraphicsLayoutWidget(self.centralwidget)
        self.pyqtgraph1.setGeometry(QtCore.QRect(290, 96, 1301, 721))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pyqtgraph1.setFont(font)
        self.pyqtgraph1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pyqtgraph1.setStyleSheet("background-color: rgb(210, 236, 255);")
        self.pyqtgraph1.setObjectName("pyqtgraph1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(54, 140, 181, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.button1.setObjectName("button1")
        self.verticalLayout.addWidget(self.button1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button7.setFont(font)
        self.button7.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.button7.setObjectName("button7")
        self.verticalLayout.addWidget(self.button7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button8.setFont(font)
        self.button8.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.button8.setObjectName("button8")
        self.verticalLayout.addWidget(self.button8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.button6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button6.setFont(font)
        self.button6.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.button6.setObjectName("button6")
        self.verticalLayout.addWidget(self.button6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(542, 66, 861, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(1360, 815, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("border-image:url();")
        self.label_time.setObjectName("label_time")
        self.label_photo = QtWidgets.QLabel(self.centralwidget)
        self.label_photo.setGeometry(QtCore.QRect(60, 3, 171, 131))
        self.label_photo.setAutoFillBackground(False)
        self.label_photo.setStyleSheet("background-color: rgb(210, 236, 255);")
        self.label_photo.setText("")
        self.label_photo.setObjectName("label_photo")
        self.groupBox4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox4.setGeometry(QtCore.QRect(1337, 225, 241, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox4.setFont(font)
        self.groupBox4.setObjectName("groupBox4")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(4, 13, 231, 91))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line4_1 = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line4_1.setFont(font)
        self.line4_1.setObjectName("line4_1")
        self.gridLayout_5.addWidget(self.line4_1, 0, 1, 1, 1)
        self.label4_1 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label4_1.setFont(font)
        self.label4_1.setObjectName("label4_1")
        self.gridLayout_5.addWidget(self.label4_1, 0, 0, 1, 1)
        self.label4_4 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label4_4.setFont(font)
        self.label4_4.setObjectName("label4_4")
        self.gridLayout_5.addWidget(self.label4_4, 0, 2, 1, 1)
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox4)
        self.layoutWidget_10.setGeometry(QtCore.QRect(3, 112, 231, 31))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button4_1 = QtWidgets.QPushButton(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button4_1.setFont(font)
        self.button4_1.setObjectName("button4_1")
        self.horizontalLayout_12.addWidget(self.button4_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.button4_2 = QtWidgets.QPushButton(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button4_2.setFont(font)
        self.button4_2.setObjectName("button4_2")
        self.horizontalLayout_12.addWidget(self.button4_2)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(1050, 225, 281, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 111, 261, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button2_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button2_1.setFont(font)
        self.button2_1.setObjectName("button2_1")
        self.horizontalLayout_5.addWidget(self.button2_1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.button2_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.button2_2.setFont(font)
        self.button2_2.setObjectName("button2_2")
        self.horizontalLayout_5.addWidget(self.button2_2)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(11, 13, 261, 91))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label2_1 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_1.setFont(font)
        self.label2_1.setObjectName("label2_1")
        self.gridLayout.addWidget(self.label2_1, 0, 0, 1, 1)
        self.line2_1 = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line2_1.setFont(font)
        self.line2_1.setObjectName("line2_1")
        self.gridLayout.addWidget(self.line2_1, 0, 1, 1, 1)
        self.label2_4 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label2_4.setFont(font)
        self.label2_4.setObjectName("label2_4")
        self.gridLayout.addWidget(self.label2_4, 0, 2, 1, 1)
        self.label2_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label2_2.setFont(font)
        self.label2_2.setObjectName("label2_2")
        self.gridLayout.addWidget(self.label2_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb2_1 = QtWidgets.QRadioButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_1.setFont(font)
        self.rb2_1.setObjectName("rb2_1")
        self.horizontalLayout_6.addWidget(self.rb2_1)
        self.rb2_2 = QtWidgets.QRadioButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_2.setFont(font)
        self.rb2_2.setObjectName("rb2_2")
        self.horizontalLayout_6.addWidget(self.rb2_2)
        self.rb2_3 = QtWidgets.QRadioButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_3.setFont(font)
        self.rb2_3.setObjectName("rb2_3")
        self.horizontalLayout_6.addWidget(self.rb2_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.label2_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_5.setFont(font)
        self.label2_5.setObjectName("label2_5")
        self.gridLayout.addWidget(self.label2_5, 1, 2, 1, 1)
        self.label2_3 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_3.setFont(font)
        self.label2_3.setObjectName("label2_3")
        self.gridLayout.addWidget(self.label2_3, 2, 0, 1, 1)
        self.combobox2_1 = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combobox2_1.setFont(font)
        self.combobox2_1.setObjectName("combobox2_1")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.gridLayout.addWidget(self.combobox2_1, 2, 1, 1, 1)
        self.label2_6 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_6.setFont(font)
        self.label2_6.setObjectName("label2_6")
        self.gridLayout.addWidget(self.label2_6, 2, 2, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setGeometry(QtCore.QRect(1050, 475, 531, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox3.setFont(font)
        self.groupBox3.setObjectName("groupBox3")
        self.groupBox3_1 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox3_1.setGeometry(QtCore.QRect(268, 13, 261, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox3_1.setFont(font)
        self.groupBox3_1.setObjectName("groupBox3_1")
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox3_1)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 31, 231, 91))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line4_2 = QtWidgets.QLineEdit(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line4_2.setFont(font)
        self.line4_2.setObjectName("line4_2")
        self.gridLayout_6.addWidget(self.line4_2, 0, 1, 1, 1)
        self.label4_2 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")
        self.gridLayout_6.addWidget(self.label4_2, 0, 0, 1, 1)
        self.label4_5 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label4_5.setFont(font)
        self.label4_5.setObjectName("label4_5")
        self.gridLayout_6.addWidget(self.label4_5, 0, 2, 1, 1)
        self.button3_1 = QtWidgets.QPushButton(self.groupBox3_1)
        self.button3_1.setGeometry(QtCore.QRect(80, 143, 91, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button3_1.setFont(font)
        self.button3_1.setObjectName("button3_1")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(12, 163, 241, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label3_2_7 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_7.setFont(font)
        self.label3_2_7.setObjectName("label3_2_7")
        self.horizontalLayout_9.addWidget(self.label3_2_7)
        self.line3_2_2 = QtWidgets.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line3_2_2.setFont(font)
        self.line3_2_2.setObjectName("line3_2_2")
        self.horizontalLayout_9.addWidget(self.line3_2_2)
        self.label3_2_8 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_8.setFont(font)
        self.label3_2_8.setObjectName("label3_2_8")
        self.horizontalLayout_9.addWidget(self.label3_2_8)
        self.line3_3_3 = QtWidgets.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line3_3_3.setFont(font)
        self.line3_3_3.setObjectName("line3_3_3")
        self.horizontalLayout_9.addWidget(self.line3_3_3)
        self.label21 = QtWidgets.QLabel(self.groupBox3)
        self.label21.setGeometry(QtCore.QRect(93, 376, 54, 12))
        self.label21.setText("")
        self.label21.setObjectName("label21")
        self.groupBox3_2 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox3_2.setGeometry(QtCore.QRect(12, 13, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox3_2.setFont(font)
        self.groupBox3_2.setObjectName("groupBox3_2")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox3_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(2, 13, 241, 131))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label3_2_1 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_1.setFont(font)
        self.label3_2_1.setObjectName("label3_2_1")
        self.gridLayout_4.addWidget(self.label3_2_1, 0, 0, 1, 1)
        self.line3_2_1 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.line3_2_1.setObjectName("line3_2_1")
        self.gridLayout_4.addWidget(self.line3_2_1, 0, 1, 1, 1)
        self.label3_2_4 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label3_2_4.setFont(font)
        self.label3_2_4.setObjectName("label3_2_4")
        self.gridLayout_4.addWidget(self.label3_2_4, 0, 2, 1, 1)
        self.label3_2_2 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label3_2_2.setFont(font)
        self.label3_2_2.setObjectName("label3_2_2")
        self.gridLayout_4.addWidget(self.label3_2_2, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rb3_2_1 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_1.setObjectName("rb3_2_1")
        self.horizontalLayout_11.addWidget(self.rb3_2_1)
        self.rb3_2_2 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_2.setObjectName("rb3_2_2")
        self.horizontalLayout_11.addWidget(self.rb3_2_2)
        self.rb3_2_3 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_3.setObjectName("rb3_2_3")
        self.horizontalLayout_11.addWidget(self.rb3_2_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
        self.label3_2_5 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_5.setFont(font)
        self.label3_2_5.setObjectName("label3_2_5")
        self.gridLayout_4.addWidget(self.label3_2_5, 1, 2, 1, 1)
        self.label3_2_3 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_3.setFont(font)
        self.label3_2_3.setObjectName("label3_2_3")
        self.gridLayout_4.addWidget(self.label3_2_3, 2, 0, 1, 1)
        self.combobox3_2_1 = QtWidgets.QComboBox(self.layoutWidget_9)
        self.combobox3_2_1.setObjectName("combobox3_2_1")
        self.combobox3_2_1.addItem("")
        self.combobox3_2_1.addItem("")
        self.combobox3_2_1.addItem("")
        self.gridLayout_4.addWidget(self.combobox3_2_1, 2, 1, 1, 1)
        self.label3_2_6 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_6.setFont(font)
        self.label3_2_6.setObjectName("label3_2_6")
        self.gridLayout_4.addWidget(self.label3_2_6, 2, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(290, 97, 741, 721))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1598, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu1 = QtWidgets.QMenu(self.menuBar)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menuBar)
        self.menu2.setObjectName("menu2")
        self.menu3 = QtWidgets.QMenu(self.menuBar)
        self.menu3.setObjectName("menu3")
        self.menu4 = QtWidgets.QMenu(self.menuBar)
        self.menu4.setObjectName("menu4")
        self.menu5 = QtWidgets.QMenu(self.menuBar)
        self.menu5.setObjectName("menu5")
        self.menu6 = QtWidgets.QMenu(self.menuBar)
        self.menu6.setObjectName("menu6")
        self.menu7 = QtWidgets.QMenu(self.menuBar)
        self.menu7.setObjectName("menu7")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action1 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action1.setIcon(icon1)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2.setIcon(icon2)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("搜索.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3.setIcon(icon3)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("历史.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action4.setIcon(icon4)
        self.action4.setObjectName("action4")
        self.action5_1 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("时域.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action5_1.setIcon(icon5)
        self.action5_1.setObjectName("action5_1")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("频域.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action5_2.setIcon(icon6)
        self.action5_2.setObjectName("action5_2")
        self.action5_3 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("滤波.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action5_3.setIcon(icon7)
        self.action5_3.setObjectName("action5_3")
        self.action5_4 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("语谱.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action5_4.setIcon(icon8)
        self.action5_4.setObjectName("action5_4")
        self.action6 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("关于.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action6.setIcon(icon9)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("关闭2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action7.setIcon(icon10)
        self.action7.setObjectName("action7")
        self.menu1.addAction(self.action1)
        self.menu1.addSeparator()
        self.menu2.addAction(self.action2)
        self.menu3.addAction(self.action3)
        self.menu4.addAction(self.action4)
        self.menu5.addAction(self.action5_1)
        self.menu5.addSeparator()
        self.menu5.addAction(self.action5_2)
        self.menu5.addSeparator()
        self.menu5.addAction(self.action5_3)
        self.menu5.addSeparator()
        self.menu5.addAction(self.action5_4)
        self.menu6.addAction(self.action6)
        self.menu7.addAction(self.action7)
        self.menuBar.addAction(self.menu1.menuAction())
        self.menuBar.addAction(self.menu2.menuAction())
        self.menuBar.addAction(self.menu3.menuAction())
        self.menuBar.addAction(self.menu4.menuAction())
        self.menuBar.addAction(self.menu5.menuAction())
        self.menuBar.addAction(self.menu6.menuAction())
        self.menuBar.addAction(self.menu7.menuAction())
        self.toolBar.addAction(self.action1)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action3)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action4)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action5_1)
        self.toolBar.addAction(self.action5_2)
        self.toolBar.addAction(self.action5_3)
        self.toolBar.addAction(self.action5_4)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action6)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action7)

        self.retranslateUi(MainWindow)
        self.button1.clicked.connect(MainWindow.progress1)
        self.button2.clicked.connect(MainWindow.progress2)
        self.button3.clicked.connect(MainWindow.progress3)
        self.button4.clicked.connect(MainWindow.progress4)
        self.button5.clicked.connect(MainWindow.progress5)
        self.button6.clicked.connect(MainWindow.progress6)
        self.button7.clicked.connect(MainWindow.progress7)
        self.button8.clicked.connect(MainWindow.progress8)
        self.button2_1.clicked.connect(MainWindow.progress9)
        self.button2_2.clicked.connect(MainWindow.progress10)
        self.button3_1.clicked.connect(MainWindow.progress11)
        self.button4_1.clicked.connect(MainWindow.progress12)
        self.button4_2.clicked.connect(MainWindow.progress13)
        self.action1.triggered.connect(MainWindow.progress1)
        self.action2.triggered.connect(MainWindow.progress7)
        self.action3.triggered.connect(MainWindow.progress8)
        self.action4.triggered.connect(MainWindow.progress6)
        self.action5_1.triggered.connect(MainWindow.progress2)
        self.action5_2.triggered.connect(MainWindow.progress3)
        self.action5_3.triggered.connect(MainWindow.progress4)
        self.action5_4.triggered.connect(MainWindow.progress5)
        self.action6.triggered.connect(MainWindow.progress14)
        self.action7.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button2.setToolTip(_translate("MainWindow", "<html><head/><body><p>随机振动信号的时域图像</p></body></html>"))
        self.button2.setText(_translate("MainWindow", "时域图像"))
        self.button3.setToolTip(_translate("MainWindow", "<html><head/><body><p>随机振动信号的频域图像</p></body></html>"))
        self.button3.setText(_translate("MainWindow", "频域图像"))
        self.button4.setToolTip(_translate("MainWindow", "<html><head/><body><p>随机振动信号的滤波后频域图像</p></body></html>"))
        self.button4.setText(_translate("MainWindow", "滤波后频域图像"))
        self.button5.setToolTip(_translate("MainWindow", "<html><head/><body><p>随机振动信号的语谱图像</p></body></html>"))
        self.button5.setText(_translate("MainWindow", "语谱图像"))
        self.button1.setToolTip(_translate("MainWindow", "<html><head/><body><p>导入WAV文件</p></body></html>"))
        self.button1.setText(_translate("MainWindow", "导入文件"))
        self.button7.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">保存检测数据</span></p></body></html>"))
        self.button7.setText(_translate("MainWindow", "保存"))
        self.button8.setToolTip(_translate("MainWindow", "<html><head/><body><p>数据库的查询、更改、删除等</p></body></html>"))
        self.button8.setText(_translate("MainWindow", "查询-更改-删除"))
        self.button6.setToolTip(_translate("MainWindow", "<html><head/><body><p>历史检测记录</p></body></html>"))
        self.button6.setText(_translate("MainWindow", "历史记录"))
        self.label_time.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox4.setTitle(_translate("MainWindow", "删除选项"))
        self.label4_1.setText(_translate("MainWindow", "输入删除序号："))
        self.label4_4.setText(_translate("MainWindow", "号"))
        self.button4_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>删除单组数据</p></body></html>"))
        self.button4_1.setText(_translate("MainWindow", "删除"))
        self.button4_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>清空数据库（慎用！）</p></body></html>"))
        self.button4_2.setText(_translate("MainWindow", "全部删除"))
        self.groupBox2.setTitle(_translate("MainWindow", "查询选项"))
        self.button2_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>查询</p></body></html>"))
        self.button2_1.setText(_translate("MainWindow", "查询"))
        self.button2_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>清空查询选项</p></body></html>"))
        self.button2_2.setText(_translate("MainWindow", "清空"))
        self.label2_1.setText(_translate("MainWindow", "隔离开关编号："))
        self.label2_4.setText(_translate("MainWindow", "号"))
        self.label2_2.setText(_translate("MainWindow", "                  第"))
        self.rb2_1.setText(_translate("MainWindow", "A"))
        self.rb2_2.setText(_translate("MainWindow", "B"))
        self.rb2_3.setText(_translate("MainWindow", "C"))
        self.label2_5.setText(_translate("MainWindow", "相"))
        self.label2_3.setText(_translate("MainWindow", "            第"))
        self.combobox2_1.setItemText(0, _translate("MainWindow", "全部"))
        self.combobox2_1.setItemText(1, _translate("MainWindow", "1"))
        self.combobox2_1.setItemText(2, _translate("MainWindow", "2"))
        self.combobox2_1.setItemText(3, _translate("MainWindow", "3"))
        self.label2_6.setText(_translate("MainWindow", "支"))
        self.groupBox3.setTitle(_translate("MainWindow", "更改选项"))
        self.groupBox3_1.setTitle(_translate("MainWindow", "原始记录"))
        self.label4_2.setText(_translate("MainWindow", "输入更改序号："))
        self.label4_5.setText(_translate("MainWindow", "号"))
        self.button3_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>更改保存记录</p></body></html>"))
        self.button3_1.setText(_translate("MainWindow", "更改"))
        self.label3_2_7.setText(_translate("MainWindow", "备注1："))
        self.label3_2_8.setText(_translate("MainWindow", "备注2："))
        self.groupBox3_2.setTitle(_translate("MainWindow", "新记录"))
        self.label3_2_1.setText(_translate("MainWindow", "隔离开关编号："))
        self.label3_2_4.setText(_translate("MainWindow", "号"))
        self.label3_2_2.setText(_translate("MainWindow", "            第"))
        self.rb3_2_1.setText(_translate("MainWindow", "A"))
        self.rb3_2_2.setText(_translate("MainWindow", "B"))
        self.rb3_2_3.setText(_translate("MainWindow", "C"))
        self.label3_2_5.setText(_translate("MainWindow", "相"))
        self.label3_2_3.setText(_translate("MainWindow", "            第"))
        self.combobox3_2_1.setItemText(0, _translate("MainWindow", "1"))
        self.combobox3_2_1.setItemText(1, _translate("MainWindow", "2"))
        self.combobox3_2_1.setItemText(2, _translate("MainWindow", "3"))
        self.label3_2_6.setText(_translate("MainWindow", "支"))
        self.menu1.setTitle(_translate("MainWindow", "文件"))
        self.menu2.setTitle(_translate("MainWindow", "保存"))
        self.menu3.setTitle(_translate("MainWindow", "查询"))
        self.menu4.setTitle(_translate("MainWindow", "历史"))
        self.menu5.setTitle(_translate("MainWindow", "处理"))
        self.menu6.setTitle(_translate("MainWindow", "关于"))
        self.menu7.setTitle(_translate("MainWindow", "退出"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action1.setText(_translate("MainWindow", "导入"))
        self.action1.setToolTip(_translate("MainWindow", "导入文件"))
        self.action1.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action2.setText(_translate("MainWindow", "保存"))
        self.action2.setToolTip(_translate("MainWindow", "保存检测记录"))
        self.action2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action3.setText(_translate("MainWindow", "查询"))
        self.action3.setToolTip(_translate("MainWindow", "查询-更改-删除操作"))
        self.action3.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action4.setText(_translate("MainWindow", "历史"))
        self.action4.setToolTip(_translate("MainWindow", "查看历史记录"))
        self.action4.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action5_1.setText(_translate("MainWindow", "时域图像"))
        self.action5_1.setToolTip(_translate("MainWindow", "查看时域图像"))
        self.action5_1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action5_2.setText(_translate("MainWindow", "频域图像"))
        self.action5_2.setToolTip(_translate("MainWindow", "查看频域图像"))
        self.action5_2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action5_3.setText(_translate("MainWindow", "滤波频域图像"))
        self.action5_3.setToolTip(_translate("MainWindow", "查看滤波频域图像"))
        self.action5_3.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.action5_4.setText(_translate("MainWindow", "语谱图像"))
        self.action5_4.setToolTip(_translate("MainWindow", "查看语谱图像"))
        self.action5_4.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.action6.setText(_translate("MainWindow", "关于"))
        self.action6.setToolTip(_translate("MainWindow", "关于软件..."))
        self.action7.setText(_translate("MainWindow", "退出"))
        self.action7.setToolTip(_translate("MainWindow", "退出桌面处理软件"))
        self.action7.setShortcut(_translate("MainWindow", "Ctrl+Z"))

from pyqtgraph import GraphicsLayoutWidget
