# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test92.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1619, 855)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bitbug_favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pyqtgraph1 = GraphicsLayoutWidget(Form)
        self.pyqtgraph1.setGeometry(QtCore.QRect(276, 130, 1301, 701))
        self.pyqtgraph1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pyqtgraph1.setObjectName("pyqtgraph1")
        self.tableWidget = QtWidgets.QTableWidget(self.pyqtgraph1)
        self.tableWidget.setGeometry(QtCore.QRect(0, -1, 741, 701))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.groupBox2 = QtWidgets.QGroupBox(self.pyqtgraph1)
        self.groupBox2.setGeometry(QtCore.QRect(760, 92, 281, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 111, 261, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button2_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button2_1.setFont(font)
        self.button2_1.setObjectName("button2_1")
        self.horizontalLayout_5.addWidget(self.button2_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.button2_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.button2_2.setFont(font)
        self.button2_2.setObjectName("button2_2")
        self.horizontalLayout_5.addWidget(self.button2_2)
        self.widget = QtWidgets.QWidget(self.groupBox2)
        self.widget.setGeometry(QtCore.QRect(11, 11, 261, 91))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label2_1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_1.setFont(font)
        self.label2_1.setObjectName("label2_1")
        self.gridLayout.addWidget(self.label2_1, 0, 0, 1, 1)
        self.line2_1 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line2_1.setFont(font)
        self.line2_1.setObjectName("line2_1")
        self.gridLayout.addWidget(self.line2_1, 0, 1, 1, 1)
        self.label2_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label2_4.setFont(font)
        self.label2_4.setObjectName("label2_4")
        self.gridLayout.addWidget(self.label2_4, 0, 2, 1, 1)
        self.label2_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label2_2.setFont(font)
        self.label2_2.setObjectName("label2_2")
        self.gridLayout.addWidget(self.label2_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb2_1 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_1.setFont(font)
        self.rb2_1.setObjectName("rb2_1")
        self.horizontalLayout_6.addWidget(self.rb2_1)
        self.rb2_2 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_2.setFont(font)
        self.rb2_2.setObjectName("rb2_2")
        self.horizontalLayout_6.addWidget(self.rb2_2)
        self.rb2_3 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rb2_3.setFont(font)
        self.rb2_3.setObjectName("rb2_3")
        self.horizontalLayout_6.addWidget(self.rb2_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.label2_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_5.setFont(font)
        self.label2_5.setObjectName("label2_5")
        self.gridLayout.addWidget(self.label2_5, 1, 2, 1, 1)
        self.label2_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_3.setFont(font)
        self.label2_3.setObjectName("label2_3")
        self.gridLayout.addWidget(self.label2_3, 2, 0, 1, 1)
        self.combobox2_1 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combobox2_1.setFont(font)
        self.combobox2_1.setObjectName("combobox2_1")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.combobox2_1.addItem("")
        self.gridLayout.addWidget(self.combobox2_1, 2, 1, 1, 1)
        self.label2_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label2_6.setFont(font)
        self.label2_6.setObjectName("label2_6")
        self.gridLayout.addWidget(self.label2_6, 2, 2, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(self.pyqtgraph1)
        self.groupBox3.setGeometry(QtCore.QRect(760, 342, 531, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox3.setFont(font)
        self.groupBox3.setObjectName("groupBox3")
        self.groupBox3_1 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox3_1.setGeometry(QtCore.QRect(11, 14, 261, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox3_1.setFont(font)
        self.groupBox3_1.setObjectName("groupBox3_1")
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox3_1)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 31, 231, 91))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line4_2 = QtWidgets.QLineEdit(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line4_2.setFont(font)
        self.line4_2.setObjectName("line4_2")
        self.gridLayout_6.addWidget(self.line4_2, 0, 1, 1, 1)
        self.label4_2 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")
        self.gridLayout_6.addWidget(self.label4_2, 0, 0, 1, 1)
        self.label4_5 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label4_5.setFont(font)
        self.label4_5.setObjectName("label4_5")
        self.gridLayout_6.addWidget(self.label4_5, 0, 2, 1, 1)
        self.button3_1 = QtWidgets.QPushButton(self.groupBox3_1)
        self.button3_1.setGeometry(QtCore.QRect(80, 146, 91, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button3_1.setFont(font)
        self.button3_1.setObjectName("button3_1")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(280, 163, 241, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label3_2_7 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_7.setFont(font)
        self.label3_2_7.setObjectName("label3_2_7")
        self.horizontalLayout_9.addWidget(self.label3_2_7)
        self.line3_2_2 = QtWidgets.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line3_2_2.setFont(font)
        self.line3_2_2.setObjectName("line3_2_2")
        self.horizontalLayout_9.addWidget(self.line3_2_2)
        self.label3_2_8 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_8.setFont(font)
        self.label3_2_8.setObjectName("label3_2_8")
        self.horizontalLayout_9.addWidget(self.label3_2_8)
        self.line3_3_3 = QtWidgets.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line3_3_3.setFont(font)
        self.line3_3_3.setObjectName("line3_3_3")
        self.horizontalLayout_9.addWidget(self.line3_3_3)
        self.label21 = QtWidgets.QLabel(self.groupBox3)
        self.label21.setGeometry(QtCore.QRect(93, 376, 54, 12))
        self.label21.setText("")
        self.label21.setObjectName("label21")
        self.groupBox3_2 = QtWidgets.QGroupBox(self.groupBox3)
        self.groupBox3_2.setGeometry(QtCore.QRect(280, 13, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox3_2.setFont(font)
        self.groupBox3_2.setObjectName("groupBox3_2")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox3_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(2, 13, 241, 131))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label3_2_1 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_1.setFont(font)
        self.label3_2_1.setObjectName("label3_2_1")
        self.gridLayout_4.addWidget(self.label3_2_1, 0, 0, 1, 1)
        self.line3_2_1 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.line3_2_1.setObjectName("line3_2_1")
        self.gridLayout_4.addWidget(self.line3_2_1, 0, 1, 1, 1)
        self.label3_2_4 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label3_2_4.setFont(font)
        self.label3_2_4.setObjectName("label3_2_4")
        self.gridLayout_4.addWidget(self.label3_2_4, 0, 2, 1, 1)
        self.label3_2_2 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label3_2_2.setFont(font)
        self.label3_2_2.setObjectName("label3_2_2")
        self.gridLayout_4.addWidget(self.label3_2_2, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rb3_2_1 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_1.setObjectName("rb3_2_1")
        self.horizontalLayout_11.addWidget(self.rb3_2_1)
        self.rb3_2_2 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_2.setObjectName("rb3_2_2")
        self.horizontalLayout_11.addWidget(self.rb3_2_2)
        self.rb3_2_3 = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.rb3_2_3.setObjectName("rb3_2_3")
        self.horizontalLayout_11.addWidget(self.rb3_2_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
        self.label3_2_5 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_5.setFont(font)
        self.label3_2_5.setObjectName("label3_2_5")
        self.gridLayout_4.addWidget(self.label3_2_5, 1, 2, 1, 1)
        self.label3_2_3 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_3.setFont(font)
        self.label3_2_3.setObjectName("label3_2_3")
        self.gridLayout_4.addWidget(self.label3_2_3, 2, 0, 1, 1)
        self.combobox3_2_1 = QtWidgets.QComboBox(self.layoutWidget_9)
        self.combobox3_2_1.setObjectName("combobox3_2_1")
        self.combobox3_2_1.addItem("")
        self.combobox3_2_1.addItem("")
        self.combobox3_2_1.addItem("")
        self.gridLayout_4.addWidget(self.combobox3_2_1, 2, 1, 1, 1)
        self.label3_2_6 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label3_2_6.setFont(font)
        self.label3_2_6.setObjectName("label3_2_6")
        self.gridLayout_4.addWidget(self.label3_2_6, 2, 2, 1, 1)
        self.groupBox4 = QtWidgets.QGroupBox(self.pyqtgraph1)
        self.groupBox4.setGeometry(QtCore.QRect(1047, 92, 241, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox4.setFont(font)
        self.groupBox4.setObjectName("groupBox4")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(2, 13, 231, 91))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line4_1 = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line4_1.setFont(font)
        self.line4_1.setObjectName("line4_1")
        self.gridLayout_5.addWidget(self.line4_1, 0, 1, 1, 1)
        self.label4_1 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label4_1.setFont(font)
        self.label4_1.setObjectName("label4_1")
        self.gridLayout_5.addWidget(self.label4_1, 0, 0, 1, 1)
        self.label4_4 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label4_4.setFont(font)
        self.label4_4.setObjectName("label4_4")
        self.gridLayout_5.addWidget(self.label4_4, 0, 2, 1, 1)
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox4)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 113, 231, 31))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button4_1 = QtWidgets.QPushButton(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button4_1.setFont(font)
        self.button4_1.setObjectName("button4_1")
        self.horizontalLayout_12.addWidget(self.button4_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.button4_2 = QtWidgets.QPushButton(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button4_2.setFont(font)
        self.button4_2.setObjectName("button4_2")
        self.horizontalLayout_12.addWidget(self.button4_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 140, 181, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.verticalLayout.addWidget(self.button1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.button7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button7.setFont(font)
        self.button7.setObjectName("button7")
        self.verticalLayout.addWidget(self.button7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.button8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button8.setFont(font)
        self.button8.setObjectName("button8")
        self.verticalLayout.addWidget(self.button8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.button6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button6.setFont(font)
        self.button6.setObjectName("button6")
        self.verticalLayout.addWidget(self.button6)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(706, 100, 411, 20))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 10, 1141, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button2 = QtWidgets.QPushButton(self.layoutWidget)
        self.button2.setObjectName("button2")
        self.horizontalLayout.addWidget(self.button2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.button3 = QtWidgets.QPushButton(self.layoutWidget)
        self.button3.setObjectName("button3")
        self.horizontalLayout.addWidget(self.button3)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.button4 = QtWidgets.QPushButton(self.layoutWidget)
        self.button4.setObjectName("button4")
        self.horizontalLayout.addWidget(self.button4)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.button5 = QtWidgets.QPushButton(self.layoutWidget)
        self.button5.setObjectName("button5")
        self.horizontalLayout.addWidget(self.button5)

        self.retranslateUi(Form)
        self.button1.clicked.connect(Form.progress1)
        self.button3.clicked.connect(Form.progress3)
        self.button4.clicked.connect(Form.progress4)
        self.button5.clicked.connect(Form.progress5)
        self.button2.clicked.connect(Form.progress2)
        self.button6.clicked.connect(Form.progress6)
        self.button7.clicked.connect(Form.progress7)
        self.button8.clicked.connect(Form.progress8)
        self.button2_1.clicked.connect(Form.progress9)
        self.button2_2.clicked.connect(Form.progress10)
        self.button3_1.clicked.connect(Form.progress11)
        self.button4_1.clicked.connect(Form.progress12)
        self.button4_2.clicked.connect(Form.progress13)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.button1, self.button2)
        Form.setTabOrder(self.button2, self.button3)
        Form.setTabOrder(self.button3, self.button4)
        Form.setTabOrder(self.button4, self.button5)
        Form.setTabOrder(self.button5, self.button7)
        Form.setTabOrder(self.button7, self.button8)
        Form.setTabOrder(self.button8, self.button6)
        Form.setTabOrder(self.button6, self.line2_1)
        Form.setTabOrder(self.line2_1, self.rb2_1)
        Form.setTabOrder(self.rb2_1, self.rb2_2)
        Form.setTabOrder(self.rb2_2, self.rb2_3)
        Form.setTabOrder(self.rb2_3, self.combobox2_1)
        Form.setTabOrder(self.combobox2_1, self.button2_1)
        Form.setTabOrder(self.button2_1, self.button2_2)
        Form.setTabOrder(self.button2_2, self.line4_1)
        Form.setTabOrder(self.line4_1, self.button4_1)
        Form.setTabOrder(self.button4_1, self.button4_2)
        Form.setTabOrder(self.button4_2, self.line4_2)
        Form.setTabOrder(self.line4_2, self.line3_2_1)
        Form.setTabOrder(self.line3_2_1, self.rb3_2_1)
        Form.setTabOrder(self.rb3_2_1, self.rb3_2_2)
        Form.setTabOrder(self.rb3_2_2, self.rb3_2_3)
        Form.setTabOrder(self.rb3_2_3, self.combobox3_2_1)
        Form.setTabOrder(self.combobox3_2_1, self.line3_2_2)
        Form.setTabOrder(self.line3_2_2, self.line3_3_3)
        Form.setTabOrder(self.line3_3_3, self.button3_1)
        Form.setTabOrder(self.button3_1, self.tableWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像处理程序"))
        self.groupBox2.setTitle(_translate("Form", "查询选项"))
        self.button2_1.setToolTip(_translate("Form", "<html><head/><body><p>查询</p></body></html>"))
        self.button2_1.setText(_translate("Form", "查询"))
        self.button2_2.setToolTip(_translate("Form", "<html><head/><body><p>清空查询选项</p></body></html>"))
        self.button2_2.setText(_translate("Form", "清空"))
        self.label2_1.setText(_translate("Form", "隔离开关编号："))
        self.label2_4.setText(_translate("Form", "号"))
        self.label2_2.setText(_translate("Form", "                  第"))
        self.rb2_1.setText(_translate("Form", "A"))
        self.rb2_2.setText(_translate("Form", "B"))
        self.rb2_3.setText(_translate("Form", "C"))
        self.label2_5.setText(_translate("Form", "相"))
        self.label2_3.setText(_translate("Form", "            第"))
        self.combobox2_1.setItemText(0, _translate("Form", "全部"))
        self.combobox2_1.setItemText(1, _translate("Form", "1"))
        self.combobox2_1.setItemText(2, _translate("Form", "2"))
        self.combobox2_1.setItemText(3, _translate("Form", "3"))
        self.label2_6.setText(_translate("Form", "支"))
        self.groupBox3.setTitle(_translate("Form", "更改选项"))
        self.groupBox3_1.setTitle(_translate("Form", "原始记录"))
        self.label4_2.setText(_translate("Form", "输入更改序号："))
        self.label4_5.setText(_translate("Form", "号"))
        self.button3_1.setToolTip(_translate("Form", "<html><head/><body><p>更改保存记录</p></body></html>"))
        self.button3_1.setText(_translate("Form", "更改"))
        self.label3_2_7.setText(_translate("Form", "备注1："))
        self.label3_2_8.setText(_translate("Form", "备注2："))
        self.groupBox3_2.setTitle(_translate("Form", "新记录"))
        self.label3_2_1.setText(_translate("Form", "隔离开关编号："))
        self.label3_2_4.setText(_translate("Form", "号"))
        self.label3_2_2.setText(_translate("Form", "            第"))
        self.rb3_2_1.setText(_translate("Form", "A"))
        self.rb3_2_2.setText(_translate("Form", "B"))
        self.rb3_2_3.setText(_translate("Form", "C"))
        self.label3_2_5.setText(_translate("Form", "相"))
        self.label3_2_3.setText(_translate("Form", "            第"))
        self.combobox3_2_1.setItemText(0, _translate("Form", "1"))
        self.combobox3_2_1.setItemText(1, _translate("Form", "2"))
        self.combobox3_2_1.setItemText(2, _translate("Form", "3"))
        self.label3_2_6.setText(_translate("Form", "支"))
        self.groupBox4.setTitle(_translate("Form", "删除选项"))
        self.label4_1.setText(_translate("Form", "输入删除序号："))
        self.label4_4.setText(_translate("Form", "号"))
        self.button4_1.setToolTip(_translate("Form", "<html><head/><body><p>删除单组数据</p></body></html>"))
        self.button4_1.setText(_translate("Form", "删除"))
        self.button4_2.setToolTip(_translate("Form", "<html><head/><body><p>清空数据库（慎用！）</p></body></html>"))
        self.button4_2.setText(_translate("Form", "全部删除"))
        self.button1.setToolTip(_translate("Form", "<html><head/><body><p>导入WAV文件</p></body></html>"))
        self.button1.setText(_translate("Form", "导入文件"))
        self.button7.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">保存数据</span></p></body></html>"))
        self.button7.setText(_translate("Form", "保存"))
        self.button8.setToolTip(_translate("Form", "<html><head/><body><p>数据库的查询、更改、删除等</p></body></html>"))
        self.button8.setText(_translate("Form", "查询-更改-删除"))
        self.button6.setToolTip(_translate("Form", "<html><head/><body><p>历史检测记录</p></body></html>"))
        self.button6.setText(_translate("Form", "历史记录"))
        self.button2.setToolTip(_translate("Form", "<html><head/><body><p>随机振动信号的时域图像</p></body></html>"))
        self.button2.setText(_translate("Form", "时域图像"))
        self.button3.setToolTip(_translate("Form", "<html><head/><body><p>随机振动信号的频域图像</p></body></html>"))
        self.button3.setText(_translate("Form", "频域图像"))
        self.button4.setToolTip(_translate("Form", "<html><head/><body><p>随机振动信号的滤波后频域图像</p></body></html>"))
        self.button4.setText(_translate("Form", "滤波后频域图像"))
        self.button5.setToolTip(_translate("Form", "<html><head/><body><p>随机振动信号的语谱图像</p></body></html>"))
        self.button5.setText(_translate("Form", "语谱图像"))

from pyqtgraph import GraphicsLayoutWidget
